export const SET_ACTION_MOVIES = 'SET_ACTION_MOVIES';
export const SET_COMEDY_MOVIES = 'SET_COMEDY_MOVIES';
export const SET_CRIME_MOVIES = 'SET_CRIME_MOVIES';
export const SET_MOVIES_DETAILS = 'SET_MOVIES_DETAILS';
export const CLEAR_MOVIE_DETAILS = 'CLEAR_MOVIE_DETAILS';

